# -*- coding: utf-8 -*-
"""h5py-data-kitchen-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lLfKgpA4_dI5bg7phOQjpTCi0XY-eNwx
"""

# Commented out IPython magic to ensure Python compatibility.
# %run ../input/python-recipes/dhtml.py
dhtml('Creating Labeled and Measured Synthetic Images')
# %run ../input/python-recipes/art_img.py

fig_size1=3.12
img_size1=img_size_display(fig_size1)
h5f1='ArtificialImages'+str(img_size1)+'.h5'
num_images1=200

data_file(num_images1,'01'+h5f1,
          fig_size1,img_size1)

# Commented out IPython magic to ensure Python compatibility.
from IPython import get_ipython;   
get_ipython().magic('reset -sf')
# %run ../input/python-recipes/art_img.py

# Commented out IPython magic to ensure Python compatibility.
fig_size1,img_size1=3.12,224
h5f1='ArtificialImages'+str(img_size1)+'.h5'
num_images1=200
data_file(num_images1,'02'+h5f1,
          fig_size1,img_size1)
from IPython import get_ipython;   
get_ipython().magic('reset -sf')
# %run ../input/python-recipes/art_img.py

dhtml('Processing Synthetic Images')

h5list1=[el for el in os.listdir('../working')
           if el[-3:]=='.h5']
dhtml(', '.join(h5list1))

x_train1,x_valid1,x_test1,\
ly_train1,ly_valid1,ly_test1,\
ty_train1,ty_valid1,ty_test1=\
h5file2data(h5list1)

num1=np.random.randint(ly_train1.shape[0])
checkplot(num1,x_train1,ly_train1,ty_train1)