# -*- coding: utf-8 -*-
"""h5py-data-kitchen-4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RvBGbY5bws3zZPrnm0qVnmFA6E41DKqF
"""

!pip install tensorflow_datasets

# Commented out IPython magic to ensure Python compatibility.
# %run ../input/python-recipes/h5file2data.py
dhtml('File Writing')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile tfdata2h5.py
# import numpy as np,os,h5py
# import tensorflow_datasets as tfds
# from tensorflow.keras.preprocessing \
# import image as tkimg
# 
# def tfdata2h5(data_name,names,num_points,img_size):
#     ds=tfds.load(data_name,split='train',
#                  shuffle_files=True,
#                  as_supervised=True)
#     h5file=data_name+str(img_size)+'.h5'
#     images=np.zeros((num_points,img_size,img_size,3),
#                      dtype='float32')
#     labels=np.zeros((num_points,),dtype='int32')
#     i=0
#     for img,lbl in ds.take(num_points):
#         img=tkimg.smart_resize(
#                 img,(img_size,img_size))
#         images[i,:]=img.numpy()/255
#         labels[i]=lbl; i+=1
#     maxlen=max([len(n) for n in names])
#     names=np.array([np.string_(name) 
#                     for name in names])
#     with h5py.File(h5file,'w') as f:
#         f.create_dataset('images',data=images,
#                          compression='gzip')
#         f.create_dataset('labels',data=labels,
#                          compression='gzip')
#         f.create_dataset('names',data=names,
#                          dtype='S%d'%maxlen,
#                          compression='gzip')
#         f.close()
#     print('\nfile size: %s'%list(os.stat(h5file))[6])
#     return h5file

# Commented out IPython magic to ensure Python compatibility.
# %run tfdata2h5.py

dhtml('Data Type #4 => TF Datasets')

data_name1='tf_flowers'
names1=['dandelion','daisy','tulips',
        'sunflowers','roses']
num_points1,img_size1=3670,128
h5file1=tfdata2h5(data_name1,names1,
                  num_points1,img_size1)

names1,x_train1,x_valid1,x_test1,\
y_train1,y_valid1,y_test1=\
h5file2data(h5file1,'spring')

display_images(x_train1,y_train1,names1,8)

data_name2='cats_vs_dogs:4.0.0'
names2=['cat','dog']
num_points2,img_size2=23000,96
h5file2=tfdata2h5(data_name2,names2,
                  num_points2,img_size2)

names2,x_train2,x_valid2,x_test2,\
y_train2,y_valid2,y_test2=\
h5file2data(h5file2,'spring')

display_images(x_train2,y_train2,names2,8)