# -*- coding: utf-8 -*-
"""h5py-data-kitchen-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tCf6MgopFHDS2GTguPIa-dLhOwWPECrR
"""

# Commented out IPython magic to ensure Python compatibility.
# %run ../input/python-recipes/dhtml.py
# %run ../input/python-recipes/multilabel_data_h5.py
dhtml('Data Type #3 => Multi-Labeled Photo Files (PNG)')

files_path1='../input/classification-of-handwritten-letters/'+\
            'zip_letters/letters/'
img_size1=32
h5file1='Letters'+str(img_size1)+'.h5'
names1=[['lowercase','uppercase'],
        [s for s in u'абвгдеёжзийклмнопрстуфхцчшщъыьэюя'],
        ['single-colored paper','striped paper',
         'squared paper','graph paper']]

data2h5file(h5file1,files_path1,img_size1,names1,
            preprocess=True,grayscale=False)

[names1,x_train1,x_valid1,x_test1,
 y_train1,y_valid1,y_test1]=\
h5file2data(h5file1,cmap='Pastel1')

display_images(x_train1,y_train1,names1,9)

files_path3='../input/style-color-images/zip_styles/'
img_size3=150
h5file3='Styles'+str(img_size3)+'.h5'
names3=[['Christian Louboutin','Chanel',
         'Dolce & Gabbana','Gucci','Christian Dior',
         'Versace','Yves Saint Laurent'],
        ['shoes','lipstick','handbag',
         'nail polish','necklace','watches',
         'ring','bracelet','boots','earrings']]

data2h5file(h5file3,files_path3,img_size3,names3,
            preprocess=True,grayscale=False)

[names3,x_train3,x_valid3,x_test3,
 y_train3,y_valid3,y_test3]=\
h5file2data(h5file3,cmap='Pastel1')

display_images(x_train3,y_train3,names3,9)

files_path4='../input/traditional-decor-patterns/'+\
            'zip_decors/'
img_size4=150
h5file4='Decors'+str(img_size4)+'.h5'
names4=[['Russia','Poland','Turkey','Belarus'],
        ['Gzhel','Khokhloma','Gorodets',
         'Wycinanki łowickie','Iznik',
         'Neglyubka','Wzory kaszubskie'],
        ['pattern','product']]

data2h5file(h5file4,files_path4,img_size4,names4,
            preprocess=True,grayscale=False)

[names4,x_train4,x_valid4,x_test4,
 y_train4,y_valid4,y_test4]=\
h5file2data(h5file4,cmap='Pastel1')

display_images(x_train4,y_train4,names4,9)

dhtml('Data Type #4 => Multi-Labeled Draw Files (PNG)')

files_path2='../input/art-pictogram/pictograms/'
img_size2=64
h5file2='Pictograms'+str(img_size2)+'.h5'
names2=[['pictogram','contour','sketch'],
        ['flower','bird','butterfly','tree',
         'plane','crane','dog','horse','deer',
         'truck','car','cat','frog',
         'ship','fish','house']]

data2h5file(h5file2,files_path2,img_size2,names2,
            preprocess=False,grayscale=False)

[names2,x_train2,x_valid2,x_test2,
 y_train2,y_valid2,y_test2]=\
h5file2data(h5file2,cmap='Pastel1')

display_images(x_train2,y_train2,names2,9)