# -*- coding: utf-8 -*-
"""h5py-data-kitchen-5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13D_5O5gcS0hU6J5B1R8MpPOhINHbMtYR
"""

# Commented out IPython magic to ensure Python compatibility.
# %run ../input/python-recipes/dhtml.py
dhtml('Pandas Data to H5Py Data')

# Commented out IPython magic to ensure Python compatibility.
import h5py,pandas as pd
from IPython.display import display,HTML
def df2h52df(df,file_name):
    thp=[('font-size','15px'),('text-align','center'),
         ('font-weight','bold'),('font-family','times'),
         ('padding','5px 5px'),('color','slategray'),
         ('background-color','silver'),('border','double white')]
    tdp=[('font-size','14px'),('padding','5px 5px'),
         ('text-align','center'),('font-family','times'),
         ('color','white'),('border','double white'),
         ('background-color','slategray')]
    style_dict=[dict(selector='th',props=thp),
                dict(selector='td',props=tdp)]
    for i in range(len(df.columns)):
        el=df.columns[i]
        elh5=el.replace('.','').lower()
        if i==0:
            df[el].to_hdf(file_name,key=elh5,mode='w')
        else:
            df[el].to_hdf(file_name,key=elh5)
    with h5py.File(file_name,'r') as f:
        keys=list(f.keys())
        display(HTML(
            '<html><style>text {color:slategray}</style><text>%s'\
#             %('features: '+str(keys))+'</text></html>'))
        series_list=[]
        for i in range(len(keys)):
            series=pd.read_hdf(file_name,keys[i])
            series_list+=[series]
        df_new=pd.concat(series_list,axis=1)
        f.close()
    display(df_new.head().T.\
            style.set_table_styles(style_dict))

dhtml('Data from External HTML Sources')

url='https://www.ecb.europa.eu/stats/policy_and_exchange_rates/'+\
    'euro_reference_exchange_rates/html/index.en.html'
file_name='exchange_rates.h5'
exchange_rates=pd.read_html(url)[0]\
.drop('Chart',axis=1)
exchange_rates.head(5).T

exchange_rates_new=df2h52df(exchange_rates,file_name)

dhtml('Data from External CSV Sources')

url='https://raw.githubusercontent.com/noahgift/'+\
    'mma/master/data/ufc_fights_all.csv'
file_name='ufc_fights.h5'
ufc_fights=pd.read_csv(url).dropna()
ufc_fights.head(5).T

ufc_fights_new=df2h52df(ufc_fights,file_name)

dhtml('Data from External JSON Sources')

url='https://data.cityofnewyork.us/resource/'+\
    'h7rb-945c.json'
file_name='school_explorer.h5'
school_explorer=pd.read_json(url)
fl=['dbn','total_students','graduation_rate','attendance_rate',
    'latitude','longitude','city','council_district']
school_explorer=school_explorer[fl]\
.dropna().astype({'council_district':'int'})
school_explorer.head(5).T

school_explorer_new=df2h52df(school_explorer,file_name)