# -*- coding: utf-8 -*-
"""recipe-writing-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qM5u5yvsm_bQefkcbE3BbSbfaq6Cgysa
"""

# %%writefile numpy_sage.py
from IPython.core.display import display,HTML
import random,numpy as np

def sage_list_plot(array,width,height,kw,kh):
    str_array=np.array2string(
        array,precision=8,separator=',',
        suppress_small=True)
    html_str="""<html><head><meta charset='utf-8'>"""+\
    """<script src='https://sagecell.sagemath.org/"""+\
    """static/embedded_sagecell.js'>"""+\
    """</script><script>$(function() {"""+\
    """sagecell.makeSagecell({inputLocation:'div.plot',"""+\
    """evalButtonText:'run',linked:true}); """+\
    """});</script></head>"""+\
    """<style>#array1.sagecell .CodeMirror-scroll {"""+\
    """min-height:3em; max-height:7em;} """+\
    """.sagecell .CodeMirror-scroll {"""+\
    """min-height:3em; max-height:10em;}</style><body>"""+\
    """<div class='plot' id='array1'><script type='text/x-sage'>"""+\
    """import numpy as np\n"""+\
    """array=np.array("""+str_array+""")\n"""+\
    """</script></div><br/>"""+\
    """<div class='plot'><script type='text/x-sage'>"""+\
    """print('array dimensions:%s'%str(array.shape))\n"""+\
    """n=array.shape[0]\n"""+\
    """p=sum([list_plot(\n"""+\
    """    array[i],color=hue(i/n),plotjoined=True,\n"""+\
    """    marker='o',markersize=2,legend_label=i+1)\n"""+\
    """       for i in range(n)])\n"""+\
    """p.show(figsize=("""+str(
        (np.round(kw*width,2),np.round(kh*height,2)))+\
    """),axes=False,\n"""+\
    """       frame=True,gridlines=True)"""+\
    """</script></div></body></html>"""
    file='sage_coderun'+str(random.uniform(0,9999999))+'.html'
    with open(file,'w') as f:
        f.write(html_str); f.close()
    string="""<div id='html_string1'><iframe src='"""+\
           file+"""' height="""+str(height+20)+\
           """ width="""+str(width+20)+"""></iframe></div>"""
    display(HTML(string))
    
def sage_list_plot_min(array,width,height,kw,kh):
    str_array=np.array2string(
        array,precision=8,separator=',',
        suppress_small=True)
    html_str="""<html><head><meta charset='utf-8'>"""+\
    """<script src='https://sagecell.sagemath.org/"""+\
    """static/embedded_sagecell.js'>"""+\
    """</script><script>$(function() {"""+\
    """sagecell.makeSagecell({inputLocation:'div.plot_min',"""+\
    """evalButtonText:'run',autoeval:true,"""+\
    """template:sagecell.templates.minimal}); """+\
    """});</script></head><body>"""+\
    """<div class='plot_min'><script type='text/x-sage'>"""+\
    """import numpy as np\n"""+\
    """array=np.array("""+str_array+""")\n"""+\
    """print('array dimensions:%s'%str(array.shape))\n"""+\
    """n=array.shape[0]\n"""+\
    """p=sum([list_plot(\n"""+\
    """    array[i],color=hue(i/n),plotjoined=True,\n"""+\
    """    marker='o',markersize=2,legend_label=i+1)\n"""+\
    """       for i in range(n)])\n"""+\
    """p.show(figsize=("""+str(
        (np.round(kw*width,2),np.round(kh*height,2)))+\
    """),axes=False,\n"""+\
    """       frame=True,gridlines=True)"""+\
    """</script></div></body></html>"""
    file='sage_coderun'+str(random.uniform(0,9999999))+'.html'
    with open(file,'w') as f:
        f.write(html_str); f.close()
    string="""<div id='html_string2'><iframe src='"""+\
           file+"""' height="""+str(height+20)+\
           """ width="""+str(width+20)+"""></iframe></div>"""
    display(HTML(string))

# Commented out IPython magic to ensure Python compatibility.
# %run numpy_sage.py

sage_list_plot(np.random.rand(4,20),520,750,.0095,.004)

sage_list_plot_min(np.random.rand(3,15),
                   520,400,.0095,.0075)