# -*- coding: utf-8 -*-
"""usage-examples-of-recipes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u1ZBoRfVubRV1_99Idq0Gz2S6RQ4KhHE
"""

# Commented out IPython magic to ensure Python compatibility.
# %run ../input/python-recipes/dhtml.py
dhtml('HTML Files Embedding','#aa33ff',f2,fs8)

import os
file_path='../input/html-recipes/'
os.listdir(file_path)

file1='animated_button.html'
with open(file_path+file1,'rb')as inputf:
    with open(file1,'wb')as outputf:
        outputf.write(inputf.read())
        outputf.close()
    inputf.close()
HTML('''<div id='data'><iframe src="'''+file1+\
     ''' " height="100" width="400"></iframe></div>''')

# Commented out IPython magic to ensure Python compatibility.
# %run ../input/python-recipes/embedding_html_string.py
file1='circle_mouse.html'
with open(file_path+file1,'r') as f:
    html_string=f.read()
    f.close()
embedding_html_string(html_string,520,520,1)

file2='interactive_tachyon_projection.html'
from IPython.display import HTML
with open(file_path+file2,'r') as f:
    html_str=f.read()
    f.close()
HTML(html_str)

from IPython.display import HTML
#file3=interactive_polar_plotting.html
html_str="""<html><head><meta charset='utf-8'>"""+\
"""<meta name='viewport' content='width=device-width'>"""+\
"""<script src='https://sagecell.sagemath.org/static/embedded_sagecell.js'>"""+\
"""</script><script>$(function(){ sagecell.makeSagecell({"""+\
"""inputLocation:'#cell1',template:sagecell.templates.minimal,"""+\
"""evalButtonText:'run'}); });</script></head><style>"""+\
"""h3 {color:#aa33ff; text-shadow:4px 4px 4px slategray;} """+\
"""pre {width:99%; padding-left:3px; border:2px double slategray;} """+\
""".sagecell_output {width:99%; border:2px double slategray; padding-right:3px;} """+\
""".sagecell_interactControlLabel:hover {padding-left:3px; color:#aa33ff; font-size:120%;} """+\
""".sagecell_interactOutput {padding-left:3px;}</style><body><h3>"""+\
"""$$\large{\mathbb{Interactive \; Polar \; Plotting}}$$</h3>"""+\
"""<p>Click the $\large{\mathbb{run}}$ button to display an example.</p>"""+\
"""<pre><code>\nc=list(colors.keys()); f(x,t)=sin(5*x)^2+0.02*t"""+\
"""\n@interact"""+\
"""\ndef _(number=[20,28,..,len(c)]):"""+\
"""\n    p=sum([polar_plot(f(x,i),(x,0,2*pi),plot_points=30,"""+\
"""\n                      thickness=1,color=c[i-1]) """+\
"""\n           for i in [1..number]])"""+\
"""\n    p.show(figsize=(5,5),gridlines=True) \n"""+\
"""</code></pre><br/>"""+\
"""<div id='cell1'><script type='text/x-sage'>"""+\
"""\nc=list(colors.keys()); f(x,t)=sin(5*x)^2+0.02*t \n@interact"""+\
"""\ndef _(number=[20,28,..,len(c)]):"""+\
"""\n    p=sum([polar_plot(f(x,i),(x,0,2*pi),plot_points=30,"""+\
"""\n                      thickness=1,color=c[i-1]) """+\
"""\n           for i in [1..number]])"""+\
"""\n    p.show(figsize=(5,5),gridlines=True)"""+\
"""</script></div></body></html>"""
HTML(html_str)

dhtml('Python Files Embedding','#aa33ff',f2,fs8)

# Commented out IPython magic to ensure Python compatibility.
# %run ../input/python-recipes/multidigraph.py
multidigraph_example()

multidigraph(
    [('1','2'),('2','3'),('3','7'),
    ('4','1'),('5','2'),('6','7')],
     5,'forestgreen')

# Commented out IPython magic to ensure Python compatibility.
# %run ../input/python-recipes/display_dataframe.py
display_dataframe_example();

# Commented out IPython magic to ensure Python compatibility.
# %run ../input/python-recipes/amplitude_wavfile.py